### ISSUE TITLE
Prevent notification on console reboot?

### ISSUE THREAD

**Issue by derekpurdy** [AngellusMortis/unifiprotect_blueprints#1]
Do you know if it's possible to block the notification as door bell ring when the console reboot?

Basically everytime I patch the unifi console and it reboots my Alexa device dings the bell like the doorbell button was pushed.

**Comment by AngellusMortis** [comment]
Not related to the blueprints. If the state changed and the blueprint fired, that means they are worked as expected. If you are having an issue with the integration, make an issue in the HA core repo.
