### ISSUE TITLE
Creating or saving an automation fails when a value is not provided for '(Optional) Alarm Entity'

### ISSUE THREAD

**Issue by dbensmith** [AngellusMortis/unifiprotect_blueprints#10]
Tested on HA Core 2024.2.5 with the [notification_smart_motion_event.yaml](https://github.com/AngellusMortis/unifiprotect_blueprints/blob/main/blueprints/automation/unifiprotect/notification_smart_motion_event.yaml) blueprint.

### Problem
Creating or saving an automation based on this blueprint fails when a value is not provided for `(Optional) Alarm Entity`.

### Reproduce
- Create or edit an automation from the blueprint.
- Do not select an entity for `(Optional) Alarm Entity`.
- Save the blueprint.

Saving will fail with the message `Message malformed: Missing input alarm_entity`:

![image](https://github.com/AngellusMortis/unifiprotect_blueprints/assets/10767946/bd36de9a-4884-4947-9a70-312da7b46426)

### Workaround
- Add any text to the `(Optional) Alarm Entity` field and save.

The field in question here appears to be required, judging by the asterisk on `Entity`.

![image](https://github.com/AngellusMortis/unifiprotect_blueprints/assets/10767946/cb413b4d-ec4e-4ef0-ad40-8c8ac4d66d0d)

**Comment by dbensmith** [comment]
@AngellusMortis

**Comment by Jjbasso** [comment]
Noticed the same thing.  The Blueprint link at https://community.home-assistant.io/t/unifi-protect-blueprints/362604 may be old. 
Just pulled it and it did not have the default '' entry to make it optimal(as I understand it).
